a = int(input("a를 입력해주세용 : "))
b = int(input("b도 입력해주세영 : "))
res = a + b
print(a, "+", b, "=", res)
res = a - b
print(a, "-", b, "=", res)
res = a * b
print(a, "*", b, "=", res)
res = a / b
print(a, "/", b, "=", res)
